-- MySQL Script generated by MySQL Workbench
-- Mon Apr 25 14:05:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema izidoctor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema izidoctor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `izidoctor` DEFAULT CHARACTER SET utf8 ;
USE `izidoctor` ;

-- -----------------------------------------------------
-- Table `izidoctor`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `valor` VARCHAR(100) NOT NULL,
  `iso3` VARCHAR(10) NOT NULL,
  `codigoMovil` VARCHAR(10) NOT NULL,
  `indicadorNacional` INT NOT NULL DEFAULT 0,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `izidoctor`.`TipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`TipoDocumento` (
  `idTipoDocumento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `nombreCorto` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `izidoctor`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidoPaterno` VARCHAR(50) NOT NULL,
  `apellidoMaterno` VARCHAR(50) NOT NULL,
  `movil` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `fechaNacimiento` DATETIME NOT NULL,
  `idPaisNacionalidad` INT NOT NULL,
  `nroDocumento` VARCHAR(50) NOT NULL,
  `idTipoDocumento` INT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Persona_Pais1_idx` (`idPaisNacionalidad` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  INDEX `fk_Persona_TipoDocumento1_idx` (`idTipoDocumento` ASC) VISIBLE,
  UNIQUE INDEX `nroDocumento_UNIQUE` (`nroDocumento` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Pais1`
    FOREIGN KEY (`idPaisNacionalidad`)
    REFERENCES `izidoctor`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_TipoDocumento1`
    FOREIGN KEY (`idTipoDocumento`)
    REFERENCES `izidoctor`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `izidoctor`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`Especialidad` (
  `idEspecialidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `indicadorActivo` INT NOT NULL DEFAULT 1,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idEspecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `izidoctor`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`Ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `idPais` INT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCiudad`),
  INDEX `fk_Ciudad_Pais_idx` (`idPais` ASC) VISIBLE,
  CONSTRAINT `fk_Ciudad_Pais`
    FOREIGN KEY (`idPais`)
    REFERENCES `izidoctor`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	\n';


-- -----------------------------------------------------
-- Table `izidoctor`.`Distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`Distrito` (
  `idDistrito` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idDistrito`),
  INDEX `fk_Distrito_Ciudad1_idx` (`Ciudad_idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_Distrito_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad`)
    REFERENCES `izidoctor`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `izidoctor`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(100) NOT NULL,
  `nombreZona` VARCHAR(100) NOT NULL,
  `referencia` VARCHAR(100) NOT NULL,
  `idPersona` INT NOT NULL,
  `idDistrito` INT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idDireccion`),
  INDEX `fk_Direccion_Persona1_idx` (`idPersona` ASC) VISIBLE,
  INDEX `fk_Direccion_Distrito1_idx` (`idDistrito` ASC) VISIBLE,
  CONSTRAINT `fk_Direccion_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `izidoctor`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direccion_Distrito1`
    FOREIGN KEY (`idDistrito`)
    REFERENCES `izidoctor`.`Distrito` (`idDistrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `izidoctor`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `contrasenia` VARCHAR(45) NOT NULL,
  `indicadorActivo` INT NOT NULL DEFAULT 1,
  `indicadorEliminado` INT NOT NULL DEFAULT 0,
  `intentosFallidos` INT NOT NULL DEFAULT 0,
  `idPersona` INT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Persona1_idx` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `izidoctor`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `izidoctor`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`Medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `contrasenia` VARCHAR(45) NOT NULL,
  `idEspecialidad` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `indicadorActivo` INT NOT NULL DEFAULT 1,
  `nroColegiado` INT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idMedico`),
  INDEX `fk_Medico_Especialidad1_idx` (`idEspecialidad` ASC) VISIBLE,
  INDEX `fk_Medico_Persona1_idx` (`idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Medico_Especialidad1`
    FOREIGN KEY (`idEspecialidad`)
    REFERENCES `izidoctor`.`Especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `izidoctor`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `izidoctor`.`CentroMedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`CentroMedico` (
  `idCentroMedico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `indicadorActivo` INT NOT NULL DEFAULT 1,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCentroMedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `izidoctor`.`CentroMedicoSucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`CentroMedicoSucursal` (
  `idCentroMedicoSucursal` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `idDistrito` INT NOT NULL,
  `indicadorActivo` INT NOT NULL DEFAULT 1,
  `referencia` VARCHAR(255) NOT NULL,
  `idMedico` INT NOT NULL,
  `idCentroMedico` INT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCentroMedicoSucursal`),
  INDEX `fk_CentroMedicoSucursal_Medico1_idx` (`idMedico` ASC) VISIBLE,
  INDEX `fk_CentroMedicoSucursal_Distrito1_idx` (`idDistrito` ASC) VISIBLE,
  INDEX `fk_CentroMedicoSucursal_CentroMedico1_idx` (`idCentroMedico` ASC) VISIBLE,
  CONSTRAINT `fk_CentroMedicoSucursal_Medico1`
    FOREIGN KEY (`idMedico`)
    REFERENCES `izidoctor`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CentroMedicoSucursal_Distrito1`
    FOREIGN KEY (`idDistrito`)
    REFERENCES `izidoctor`.`Distrito` (`idDistrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CentroMedicoSucursal_CentroMedico1`
    FOREIGN KEY (`idCentroMedico`)
    REFERENCES `izidoctor`.`CentroMedico` (`idCentroMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `izidoctor`.`HorarioMedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`HorarioMedico` (
  `idHorarioMedico` INT NOT NULL AUTO_INCREMENT,
  `horaInicio` DATETIME NOT NULL,
  `duracion` INT NOT NULL,
  `idMedico` INT NOT NULL,
  `indicadorActivo` INT NOT NULL DEFAULT 1,
  `idCentroMedicoSucursal` INT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idHorarioMedico`),
  INDEX `fk_HorarioMedico_Medico1_idx` (`idMedico` ASC) VISIBLE,
  INDEX `fk_HorarioMedico_CentroMedicoSucursal1_idx` (`idCentroMedicoSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_HorarioMedico_Medico1`
    FOREIGN KEY (`idMedico`)
    REFERENCES `izidoctor`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HorarioMedico_CentroMedicoSucursal1`
    FOREIGN KEY (`idCentroMedicoSucursal`)
    REFERENCES `izidoctor`.`CentroMedicoSucursal` (`idCentroMedicoSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `izidoctor`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izidoctor`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idHorarioMedico` INT NOT NULL,
  `idMedico` INT NOT NULL,
  `indicadorActivo` INT NOT NULL DEFAULT 1,
  `indicadorCancelado` INT NOT NULL DEFAULT 0,
  `fechaCreacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Reserva_HorarioMedico1_idx` (`idHorarioMedico` ASC) VISIBLE,
  INDEX `fk_Reserva_Medico1_idx` (`idMedico` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `izidoctor`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_HorarioMedico1`
    FOREIGN KEY (`idHorarioMedico`)
    REFERENCES `izidoctor`.`HorarioMedico` (`idHorarioMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Medico1`
    FOREIGN KEY (`idMedico`)
    REFERENCES `izidoctor`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
