USE IZIDOCTOR;
INSERT INTO tipodocumento (NOMBRE, NOMBRECORTO, VALOR) 
VALUES
	("DOCUMENTO NACIONAL DE IDENTIDAD", "D.N.I", "DNI"),
    ("CARNET DE EXTRANJERIA", "C.E.", "CE"),
    ("PASAPORTE", "P.S.", "PS")